services:

    webdav.nextcloud_client:
        class: Sabre\DAV\Client
        arguments:
            - {baseUri: "%nextcloud_webdav_uri%", userName: "%nextcloud_username%", password: "%nextcloud_password%"}

    netbs.galerie.mapper:
        class: GalerieBundle\Service\GalerieMapper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@liip_imagine.cache.manager"
            - "@liip_imagine.service.filter"

    netbs.galerie.tree:
        class: GalerieBundle\Service\GalerieTree
        arguments:
            - "@doctrine.orm.entity_manager"