services:

    galerie:
        class: GalerieBundle\Service\Galerie
        arguments:
            - "@netbs.params"

    galerie.imagine.cache_resolver:
        class: GalerieBundle\Imagine\EtagCacheResolver
        arguments:
            - "%kernel.project_dir%"
            - "%web_path%"
            - "@doctrine.orm.entity_manager"
            - "@filesystem"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: netbs_cache_resolver }

    galerie.nextcloud_bridge:
        class: GalerieBundle\Service\NextcloudBridge
        arguments:
            - "@webdav.nextcloud_client"

    webdav.nextcloud_client:
        class: Sabre\DAV\Client
        arguments:
            - {baseUri: "%nextcloud_webdav_uri%", userName: "%nextcloud_username%", password: "%nextcloud_password%"}

    galerie.mapper:
        class: GalerieBundle\Service\GalerieMapper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@liip_imagine.cache.manager"
            - "@liip_imagine.service.filter"
            - "@netbs.params"
            - "@webdav.nextcloud_client"
            - "@galerie.tree"

    galerie.tree:
        class: GalerieBundle\Service\GalerieTree
        arguments:
            - "@doctrine.orm.entity_manager"

    galerie.listener.main_menu:
        class: GalerieBundle\Listener\MainMenuListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: netbs.menu.extend, method: onMenuConfigure }

    galerie.list_model.directories:
        class: GalerieBundle\ListModel\DirectoriesList
        tags:
            - { name: netbs.list.model }

    galerie.serializer.media_normalizer:
        class: GalerieBundle\Serializer\MediaNormalizer
        arguments:
            - "@liip_imagine.cache.manager"
        tags:
            - { name: serializer.normalizer }

    galerie.serializer.directory_normalizer:
        class: GalerieBundle\Serializer\DirectoryNormalizer
        arguments:
            - "@galerie.tree"
            - "@liip_imagine.cache.manager"
        tags:
            - { name: serializer.normalizer }