services:

    webdav.nextcloud_client:
        class: Sabre\DAV\Client
        arguments:
            - {baseUri: "%nextcloud_webdav_uri%", userName: "%nextcloud_username%", password: "%nextcloud_password%"}

    galerie.mapper:
        class: GalerieBundle\Service\GalerieMapper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@liip_imagine.cache.manager"
            - "@liip_imagine.service.filter"

    galerie.tree:
        class: GalerieBundle\Service\GalerieTree
        arguments:
            - "@doctrine.orm.entity_manager"

    galerie.listener.main_menu:
        class: GalerieBundle\Listener\MainMenuListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: netbs.menu.extend, method: onMenuConfigure }

    galerie.list_model.directories:
        class: GalerieBundle\ListModel\DirectoriesList
        tags:
            - { name: netbs.list.model }

    galerie.serializer.media_normalizer:
        class: GalerieBundle\Serializer\MediaNormalizer
        arguments:
            - "@liip_imagine.cache.manager"
        tags:
            - { name: serializer.normalizer }

    galerie.serializer.directory_normalizer:
        class: GalerieBundle\Serializer\DirectoryNormalizer
        arguments:
            - "@galerie.tree"
            - "@liip_imagine.cache.manager"
        tags:
            - { name: serializer.normalizer }