services:

    netbs.secure.security.voter.user:
        class: NetBS\SecureBundle\Voter\UserVoter
        arguments:
            - "@netbs.secure.config"
        tags:
            - { name: security.voter }

    netbs.secure.security.voter.autorisation:
        class: NetBS\SecureBundle\Voter\AutorisationVoter
        arguments:
        - "@netbs.secure.config"
        tags:
        - { name: security.voter }

    netbs.secure.security.voter.bs_roles:
        class: NetBS\SecureBundle\Voter\BSRoleVoter
        arguments:
            - "@netbs.secure.config"
        tags:
            - { name: security.voter }

    netbs.secure.security.voter.roles:
        class: NetBS\SecureBundle\Voter\RoleVoter
        tags:
            - { name: security.voter }