sysmoh_db_task:
    resource: "@SysmohDBTaskBundle/Controller/"
    type:     annotation
    prefix:   /

galerie:
    resource: "@GalerieBundle/Controller/"
    type:     annotation
    prefix:   /

sauvabelin:
    resource: "@SauvabelinBundle/Controller/"
    type:     annotation
    prefix:   /netBS/bs


netbs:
    resource: '@NetBSCoreBundle/Resources/config/routing.yml'
    prefix: /netBS