ovesco_galerie:
    resource: "@OvescoGalerieBundle/ApiController/"
    type:     annotation
    prefix:   /

ovesco_facturation_api:
    resource: "@OvescoFacturationBundle/ApiController/"
    type:     annotation
    prefix:   /facturation

sauvabelin:
    resource: "@SauvabelinBundle/Controller/"
    type:     annotation
    prefix:   /netBS/bs

netbs:
    resource: '@NetBSCoreBundle/Resources/config/routing.yml'
    prefix: /netBS

netbs_api:
    resource: '@NetBSCoreBundle/Resources/config/routing_api.yml'
    prefix: /api/v1/netBS

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /netBS
        permanent: true