services:

    sauvabelin.list.rule_mailing_lists:
        class: SauvabelinBundle\ListModel\RuleMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.redirect_mailing_lists:
        class: SauvabelinBundle\ListModel\RedirectMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.displayable_mailing_lists:
        class: SauvabelinBundle\ListModel\DisplayableMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.news:
        class: SauvabelinBundle\ListModel\NewsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.news_channels:
        class: SauvabelinBundle\ListModel\NewsChannelsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.latest_accounts:
        class: SauvabelinBundle\ListModel\LatestAccountsCreatedList
        tags:
            - { name: netbs.list.model }