bs:
    fonction.commandant_id:             -1
    fonction.secretaire_general_id:     -1

    fonction.louveteau_id:              -1
    fonction.eclaireur_id:              -1

    fonction.weight.user_account:       100
    fonction.weight.mail_redirect:      500
    fonction.weight.mailbox:            1000
