bs:
    fonction.commandant_id:             -1
    fonction.secretaire_general_id:     -1

    fonction.louveteau_id:              -1
    fonction.eclaireur_id:              -1

    fonction.weight.user_account:       100
    fonction.weight.mail_redirect:      500
    fonction.weight.mailbox:            1000

    groupe.branche_eclaireurs_id:       -1
    groupe.branche_eclaireuses_id:      -1
    groupe.branche_louveteaux_id:       -1
    groupe.branche_louvettes_id:        -1

    groupe_categorie.unite_id:          -1