imports:
    - { resource: lists.yml }

services:

    pheanstalk:
        class: Pheanstalk\Pheanstalk
        arguments:
            - "%pheanstalk_url%"

    sauvabelin.exporter.liste_unite:
        class: SauvabelinBundle\Exporter\PDFUnite
        arguments:
            - "@netbs.fichier.config"
        tags:
            - { name: netbs.exporter }

    sauvabelin.isp_config_manager:
        class: SauvabelinBundle\Service\ISPConfigManager
        arguments:
            - "%ispconfig_host%"
            - "%ispconfig_user%"
            - "%ispconfig_password%"
            - "%ispconfig_maildir%"
            - "%ispconfig_homedir%"
            - "%ispconfig_client_id%"
            - "%ispconfig_server_id%"
            - "%ispconfig_uid%"
            - "%ispconfig_gid%"

    sauvabelin.command.post_install:
        class: SauvabelinBundle\Command\PostInstallCommand
        tags:
            - { name: console.command }
            - { name: netbs.post_install_script }

    sauvabelin.subscriber.doctrine_user:
        class: SauvabelinBundle\Subscriber\DoctrineUserAccountSubscriber
        arguments:
            - "@security.password_encoder"
            - "@netbs.mailer"
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sauvabelin.subscriber.event_user:
        class: SauvabelinBundle\Subscriber\EventUserAccountSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }

    sauvabelin.form.membre_extension:
        class: SauvabelinBundle\Form\MembreTypeExtension
        tags:
            - { name: form.type_extension, extended_type: NetBS\FichierBundle\Form\Personne\MembreType }

    sauvabelin.listener.main_menu:
        class: SauvabelinBundle\Listener\MainMenuListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: netbs.menu.extend, method: onMenuConfigure }

    sauvabelin.listener.dashboard_layout:
        class: SauvabelinBundle\Listener\DashboardListener
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: netbs.block.pre_render_layout, method: extendsDashboard }

    sauvabelin.listener.page_groupe_layout:
        class: SauvabelinBundle\Listener\PageGroupeListener
        arguments:
            - "@request_stack"
            - "@netbs.params"
            - "@twig"
        tags:
            - { name: kernel.event_listener, event: netbs.block.pre_render_layout, method: extendsPageGroupe }


    sauvabelin.voter.mailing_lists:
        class: SauvabelinBundle\Voter\MailingListVoter
        tags:
            - { name: security.voter }

    sauvabelin.form.type.news_channel:
        class: SauvabelinBundle\Form\Type\NewsChannelType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type }

    sauvabelin.voter.news:
        class: SauvabelinBundle\Voter\NewsVoter
        tags:
            - { name: security.voter }

    sauvabelin.serializer.news_normalizer:
        class: SauvabelinBundle\Serializer\NewsNormalizer
        tags:
            - { name: serializer.normalizer }

#    sauvabelin.subscriber.mailing_lists:
#        class: SauvabelinBundle\Subscriber\MailingListSubscriber
#        arguments:
#            - "@sauvabelin.isp_config_manager"
#        tags:
#            - { name: doctrine.event_subscriber }


#    sauvabelin.subscriber.user:
#        class: SauvabelinBundle\Subscriber\UserSubscriber
#        arguments:
#            - "@sauvabelin.isp_config_manager"
#            - "@request_stack"
#            - "@doctrine.orm.entity_manager"
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#            - { name: kernel.event_listener, event: netbs.secure.event.user_password_change, method: userPasswordChange }


    sauvabelin.listener.verify_user_password_change:
        class: SauvabelinBundle\Listener\ForceNewPasswordListener
        arguments:
            - "@security.token_storage"
            - "@router"
            - "@session"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: verifyUser }