services:

    ovesco.facturation.subscribers.doctrine_debiteur:
        class: Ovesco\FacturationBundle\Subscriber\DoctrineDebiteurSubscriber
        arguments:
            - "@netbs.fichier.config"
        tags:
            - { name: doctrine.event_subscriber }

    ovesco.facturation.exporter.pdf_factures:
        class: Ovesco\FacturationBundle\Exporter\PDFFacture
        tags:
            - { name: netbs.exporter }