services:

    form.extension.errors:
        class: NetBS\CoreBundle\Form\FormErrorExtension
        arguments:
            - "@session"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    form.type.datepicker:
        class: NetBS\CoreBundle\Form\Type\DatepickerType
        arguments:
            - "@netbs.params"
        tags:
            - { name: form.type }

    form.type.switch:
        class: NetBS\CoreBundle\Form\Type\SwitchType
        tags:
            - { name: form.type }

    form.type.date_mask:
        class: NetBS\CoreBundle\Form\Type\DateMaskType
        arguments:
            - "@netbs.params"
        tags:
            - { name: form.type }

    form.type.quill:
        class: NetBS\CoreBundle\Form\Type\QuillType
        tags:
            - { name: form.type }

    form.type.trumbowyg:
        class: NetBS\CoreBundle\Form\Type\TrumbowygType
        tags:
            - { name: form.type }

    form.type.select2_document:
        class: NetBS\CoreBundle\Form\Type\Select2DocumentType
        tags:
            - { name: form.type }

    form.type.ajax_select2_document:
        class: NetBS\CoreBundle\Form\Type\AjaxSelect2DocumentType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@netbs.core.select2_providers_manager"
        tags:
            - { name: form.type }