services:

    ovesco.galerie.imagine.cache_resolver:
        class: Ovesco\GalerieBundle\Imagine\GalerieCacheResolver
        arguments:
            - "%kernel.project_dir%"
            - "%ovesco.galerie.cache_prefix%"
            - "@ovesco.galerie.config"
            - "@filesystem"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: ovesco.galerie_cache_resolver }
